//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapThis.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapThis.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _01_Before {
            get {
                return ResourceManager.GetString("_01_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _01_Refactored {
            get {
                return ResourceManager.GetString("_01_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item, int a)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _02_Before {
            get {
                return ResourceManager.GetString("_02_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item, int a)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _02_Refactored {
            get {
                return ResourceManager.GetString("_02_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        protected static Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _03_Before {
            get {
                return ResourceManager.GetString("_03_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        protected static Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _03_Refactored {
            get {
                return ResourceManager.GetString("_03_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    using MapThis.Tests.Children;
        ///
        ///    public class Parent { public Child Child { get; set; } }
        ///    public class ParentDto { public ChildDto Child { get; set; } }
        ///}
        ///namespace MapThis.Tests.Children
        ///{
        ///    public class Child { public int Id {  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _04_Before {
            get {
                return ResourceManager.GetString("_04_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///using MapThis.Tests.Children;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private Child Map(ChildDto item)
        ///        {
        ///            var newItem = new Child()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return new [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _04_Refactored {
            get {
                return ResourceManager.GetString("_04_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    using MapThis.Tests.Children;
        ///    using System.Collections.Generic;
        ///
        ///    public class Parent { public IList&lt;Child&gt; Child { get; set; } }
        ///    public class ParentDto { public IList&lt;ChildDto&gt; Child { get; set; } }
        ///}
        ///namespace MapThis.Tests.C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _05_Before {
            get {
                return ResourceManager.GetString("_05_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///using MapThis.Tests.Children;
        ///using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private IList&lt;Child&gt; Map(IList&lt;ChildDto&gt; source)
        ///        {
        ///            var destination = new List&lt;Child&gt;();
        ///
        ///            foreach (v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _05_Refactored {
            get {
                return ResourceManager.GetString("_05_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    public class Parent { public Child Child { get; set; } }
        ///    public class ParentDto { public ChildDto Child { get; set; } }
        ///}
        ///namespace MapThis
        ///{
        ///    public class Child { public int Id { get; set; } }
        ///    public class ChildDto { public in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _06_Before {
            get {
                return ResourceManager.GetString("_06_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private Child Map(ChildDto item)
        ///        {
        ///            var newItem = new Child()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///}
        ///nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _06_Refactored {
            get {
                return ResourceManager.GetString("_06_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        [Custom]
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///    public class CustomAttribute : Attribute { }
        ///}.
        /// </summary>
        internal static string _07_Before {
            get {
                return ResourceManager.GetString("_07_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        [Custom]
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///    public class CustomAttribute : Attribute { }
        ///}.
        /// </summary>
        internal static string _07_Refactored {
            get {
                return ResourceManager.GetString("_07_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public static Parent [||]Map(ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public Child Child { get; set; } }
        ///    public class ParentDto { public ChildDto Child { get; set; } }
        ///    public class Child { public int Id { get; set; } }
        ///    public class ChildDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _08_Before {
            get {
                return ResourceManager.GetString("_08_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public static Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private static Child Map(ChildDto item)
        ///        {
        ///            var newItem = new Child()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _08_Refactored {
            get {
                return ResourceManager.GetString("_08_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [||]Map(ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public IList&lt;Child&gt; Child { get; set; } }
        ///    public class ParentDto { public IList&lt;ChildDto&gt; Child { get; set; } }
        ///    public class Child { public int Id { get; set; } }
        ///    public class ChildDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _09_Before {
            get {
                return ResourceManager.GetString("_09_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private IList&lt;Child&gt; Map(IList&lt;ChildDto&gt; source)
        ///        {
        ///            var destination = new List&lt;Child&gt;();
        ///
        ///            foreach (var item in source)
        ///            {
        ///                destinatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _09_Refactored {
            get {
                return ResourceManager.GetString("_09_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public IList&lt;Parent&gt; [|Map|](IList&lt;ParentDto&gt; item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _10_Before {
            get {
                return ResourceManager.GetString("_10_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public IList&lt;Parent&gt; Map(IList&lt;ParentDto&gt; item)
        ///        {
        ///            var destination = new List&lt;Parent&gt;();
        ///
        ///            foreach (var item2 in item)
        ///            {
        ///                destination.Add(Map(item2));
        ///            }
        ///
        ///            return destination;
        ///        }
        ///
        ///        private Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10_Refactored {
            get {
                return ResourceManager.GetString("_10_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public IList&lt;Parent&gt; [|Map|](IList&lt;ParentDto&gt; dto, int item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _11_Before {
            get {
                return ResourceManager.GetString("_11_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public IList&lt;Parent&gt; Map(IList&lt;ParentDto&gt; dto, int item)
        ///        {
        ///            var destination = new List&lt;Parent&gt;();
        ///
        ///            foreach (var item2 in dto)
        ///            {
        ///                destination.Add(Map(item2));
        ///            }
        ///
        ///            return destination;
        ///        }
        ///
        ///        private Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11_Refactored {
            get {
                return ResourceManager.GetString("_11_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public IList&lt;Parent&gt; [|Map|](IList&lt;ParentDto&gt; dto, int item, int item2)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _12_Before {
            get {
                return ResourceManager.GetString("_12_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public IList&lt;Parent&gt; Map(IList&lt;ParentDto&gt; dto, int item, int item2)
        ///        {
        ///            var destination = new List&lt;Parent&gt;();
        ///
        ///            foreach (var item3 in dto)
        ///            {
        ///                destination.Add(Map(item3));
        ///            }
        ///
        ///            return destination;
        ///        }
        ///
        ///        private Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12_Refactored {
            get {
                return ResourceManager.GetString("_12_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item, int newItem)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _13_Before {
            get {
                return ResourceManager.GetString("_13_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item, int newItem)
        ///        {
        ///            var newItem2 = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem2;
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _13_Refactored {
            get {
                return ResourceManager.GetString("_13_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public IList&lt;Parent&gt; [|Map|](IList&lt;ParentDto&gt; dto, int destination)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _14_Before {
            get {
                return ResourceManager.GetString("_14_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public IList&lt;Parent&gt; Map(IList&lt;ParentDto&gt; dto, int destination)
        ///        {
        ///            var destination2 = new List&lt;Parent&gt;();
        ///
        ///            foreach (var item in dto)
        ///            {
        ///                destination2.Add(Map(item));
        ///            }
        ///
        ///            return destination2;
        ///        }
        ///
        ///        private Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _14_Refactored {
            get {
                return ResourceManager.GetString("_14_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///
        ///        public int Test()
        ///        {
        ///            return 0;
        ///        }
        ///    }
        ///    public class Parent { public Child Child { get; set; } }
        ///    public class ParentDto { public ChildDto Child { get; set; } }
        ///    public class Child { public int Id { get; set; } }
        ///    public class ChildDto { public int Id { get; set; } }
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _15_Before {
            get {
                return ResourceManager.GetString("_15_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        public int Test()
        ///        {
        ///            return 0;
        ///        }
        ///
        ///        private Child Map(ChildDto item)
        ///        {
        ///            var newItem = new Child()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _15_Refactored {
            get {
                return ResourceManager.GetString("_15_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    using MapThis.Tests.Children;
        ///    using System.Collections.Generic;
        ///
        ///    public class Parent { public ICollection&lt;Child&gt; Child { get; set; } }
        ///    public class ParentDto { public ICollection&lt;ChildDto&gt; Child { get; set; } }
        ///}
        ///namespace Map [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _16_Before {
            get {
                return ResourceManager.GetString("_16_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///using MapThis.Tests.Children;
        ///using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private ICollection&lt;Child&gt; Map(ICollection&lt;ChildDto&gt; source)
        ///        {
        ///            var destination = new List&lt;Child&gt;();
        ///
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _16_Refactored {
            get {
                return ResourceManager.GetString("_16_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    using MapThis.Tests.Children;
        ///
        ///    public class Parent { public Child Child { get; set; } }
        ///    public class ParentDto { public ChildDto Child { get; set; } }
        ///}
        ///namespace MapThis.Tests.Children
        ///{
        ///    public class Child { public int Id {  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _17_Before {
            get {
                return ResourceManager.GetString("_17_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///using MapThis.Tests.Children;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            if (item == null) return null;
        ///
        ///            var newItem = new Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private Child Map(ChildDto item)
        ///        {
        ///            if (item == null) return null;
        ///
        ///            var newItem = new Chi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _17_Refactored {
            get {
                return ResourceManager.GetString("_17_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    using MapThis.Tests.Children;
        ///    using System.Collections.Generic;
        ///
        ///    public class Parent { public IList&lt;Child&gt; Child { get; set; } }
        ///    public class ParentDto { public IList&lt;ChildDto&gt; Child { get; set; } }
        ///}
        ///namespace MapThis.Tests.C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _18_Before {
            get {
                return ResourceManager.GetString("_18_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///using MapThis.Tests.Children;
        ///using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            if (item == null) return null;
        ///
        ///            var newItem = new Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private IList&lt;Child&gt; Map(IList&lt;ChildDto&gt; source)
        ///        {
        ///            var destination  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _18_Refactored {
            get {
                return ResourceManager.GetString("_18_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](IList&lt;ParentDto&gt; item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests
        ///{
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _19_Before {
            get {
                return ResourceManager.GetString("_19_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public IList&lt;Parent&gt; [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests
        ///{
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _20_Before {
            get {
                return ResourceManager.GetString("_20_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///    public class Parent { public IList&lt;Child&gt; Children { get; set; } public GrandChild GrandChild { get; set; } }
        ///    public class ParentDto { public IList&lt;ChildDto&gt; Children { get; set; } public GrandChildDto GrandChild { get; set; } }
        ///    public class Child { public GrandChild  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _21_Before {
            get {
                return ResourceManager.GetString("_21_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Children = Map(item.Children),
        ///                GrandChild = Map(item.GrandChild),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private IList&lt;Child&gt; Map(IList&lt;ChildDto&gt; source)
        ///        {
        ///            var destination = new List&lt;Child&gt;();
        ///
        ///            foreach (var  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _21_Refactored {
            get {
                return ResourceManager.GetString("_21_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///
        ///        private Child Map(ChildDto item)
        ///        {
        ///            var newItem = new Child()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent { public IList&lt;Child&gt; Children { get; set; } }
        ///    public c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _22_Before {
            get {
                return ResourceManager.GetString("_22_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Children = Map(item.Children),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private IList&lt;Child&gt; Map(IList&lt;ChildDto&gt; source)
        ///        {
        ///            var destination = new List&lt;Child&gt;();
        ///
        ///            foreach (var item in source)
        ///            {
        ///                dest [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _22_Refactored {
            get {
                return ResourceManager.GetString("_22_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parents.Parent [|Map|](Parents.ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _23_Before {
            get {
                return ResourceManager.GetString("_23_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parents.Parent Map(Parents.ParentDto item)
        ///        {
        ///            var newItem = new Parents.Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _23_Refactored {
            get {
                return ResourceManager.GetString("_23_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.InvalidOperationException();
        ///        }
        ///    }
        ///    public class Parent { public int? Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _24_Before {
            get {
                return ResourceManager.GetString("_24_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent { public int? Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _24_Refactored {
            get {
                return ResourceManager.GetString("_24_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto item)
        ///        {
        ///            throw new System.InvalidOperationException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int? Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _25_Before {
            get {
                return ResourceManager.GetString("_25_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int? Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _25_Refactored {
            get {
                return ResourceManager.GetString("_25_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map[|(|]ParentDto item)
        ///        {
        ///            throw new System.InvalidOperationException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _26_Before {
            get {
                return ResourceManager.GetString("_26_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _26_Refactored {
            get {
                return ResourceManager.GetString("_26_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public [|Parent|] Map(ParentDto item)
        ///        {
        ///            throw new System.InvalidOperationException();
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _27_Before {
            get {
                return ResourceManager.GetString("_27_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _27_Refactored {
            get {
                return ResourceManager.GetString("_27_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using P = MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public P.Parent [|Map|](P.ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    public class Parent { public Child Child { get; set; } }
        ///    public class ParentDto { public ChildDto Child { get; set; } }
        ///    public class Child { public int Id { get; set; } }
        ///    public class ChildDto { public int Id { get; set;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _28_Before {
            get {
                return ResourceManager.GetString("_28_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using P = MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public P.Parent Map(P.ParentDto item)
        ///        {
        ///            var newItem = new P.Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private P.Child Map(P.ChildDto item)
        ///        {
        ///            var newItem = new P.Child()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _28_Refactored {
            get {
                return ResourceManager.GetString("_28_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using P = MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class2
        ///    {
        ///        public IList&lt;P.Parent&gt; [|Map|](IList&lt;P.ParentDto&gt; item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _29_Before {
            get {
                return ResourceManager.GetString("_29_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using P = MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class2
        ///    {
        ///        public IList&lt;P.Parent&gt; Map(IList&lt;P.ParentDto&gt; item)
        ///        {
        ///            var destination = new List&lt;P.Parent&gt;();
        ///
        ///            foreach (var item2 in item)
        ///            {
        ///                destination.Add(Map(item2));
        ///            }
        ///
        ///            return destination;
        ///        }
        ///
        ///        private P.Parent Map(P.ParentDto item)
        ///        {
        ///            var newItem = new  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _29_Refactored {
            get {
                return ResourceManager.GetString("_29_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent1 [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///}
        ///}
        ///namespace MapThis.Tests
        ///{
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _30_Before {
            get {
                return ResourceManager.GetString("_30_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](ParentDto1 item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///}
        ///}
        ///namespace MapThis.Tests
        ///{
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _31_Before {
            get {
                return ResourceManager.GetString("_31_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public BaseClass&lt;Parent&gt; [|Map|](ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests
        ///{
        ///    public class BaseClass&lt;T&gt; { public int Id { get; set; } }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _32_Before {
            get {
                return ResourceManager.GetString("_32_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public BaseClass&lt;Parent&gt; Map(ParentDto item)
        ///        {
        ///            var newItem = new BaseClass&lt;Parent&gt;()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests
        ///{
        ///    public class BaseClass&lt;T&gt; { public int Id { get; set; } }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _32_Refactored {
            get {
                return ResourceManager.GetString("_32_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent [|Map|](BaseClass&lt;ParentDto&gt; item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests
        ///{
        ///    public class BaseClass&lt;T&gt; { public int Id { get; set; } }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _33_Before {
            get {
                return ResourceManager.GetString("_33_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent Map(BaseClass&lt;ParentDto&gt; item)
        ///        {
        ///            var newItem = new Parent()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests
        ///{
        ///    public class BaseClass&lt;T&gt; { public int Id { get; set; } }
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _33_Refactored {
            get {
                return ResourceManager.GetString("_33_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parents.Parent [|Map|](Parents.ParentDto item)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    public class Parent { public Child Child { get; set; } }
        ///    public class ParentDto { public ChildDto Child { get; set; } }
        ///    public class Child { public int Id { get; set; } }
        ///    public class ChildDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _34_Before {
            get {
                return ResourceManager.GetString("_34_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parents.Parent Map(Parents.ParentDto item)
        ///        {
        ///            var newItem = new Parents.Parent()
        ///            {
        ///                Child = Map(item.Child),
        ///            };
        ///
        ///            return newItem;
        ///        }
        ///
        ///        private Parents.Child Map(Parents.ChildDto item)
        ///        {
        ///            var newItem = new Parents.Child()
        ///            {
        ///                Id = item.Id,
        ///            };
        ///
        ///            return newItem;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _34_Refactored {
            get {
                return ResourceManager.GetString("_34_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public abstract class Class1
        ///    {
        ///        public abstract Parent [|Map|](ParentDto item);
        ///    }
        ///}
        ///namespace MapThis.Tests
        ///{
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _35_Before {
            get {
                return ResourceManager.GetString("_35_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent[] Map(ParentDto[] source)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///namespace MapThis.Tests.Parents
        ///{
        ///    public class Parent { public int Id { get; set; } }
        ///    public class ParentDto { public int Id { get; set; } }
        ///}
        ///.
        /// </summary>
        internal static string _36_Before {
            get {
                return ResourceManager.GetString("_36_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MapThis.Tests.Parents;
        ///using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public Parent[] Map(ParentDto[] source)
        ///        {
        ///            var destination = new List&lt;Parent&gt;();
        ///
        ///            foreach (var item in source)
        ///            {
        ///                destination.Add(Map(item));
        ///            }
        ///
        ///            return destination.ToArray();
        ///        }
        ///
        ///        private Parent Map(ParentDto item)
        ///        {
        ///            var newItem = new Parent()
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _36_Refactored {
            get {
                return ResourceManager.GetString("_36_Refactored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public string[] Map(string[] source)
        ///        {
        ///            throw new System.NotImplementedException();
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _37_Before {
            get {
                return ResourceManager.GetString("_37_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MapThis.Tests
        ///{
        ///    public class Class1
        ///    {
        ///        public string[] Map(string[] source)
        ///        {
        ///            var destination = new List&lt;string&gt;();
        ///
        ///            foreach (var item in source)
        ///            {
        ///                destination.Add(item);
        ///            }
        ///
        ///            return destination.ToArray();
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _37_Refactored {
            get {
                return ResourceManager.GetString("_37_Refactored", resourceCulture);
            }
        }
    }
}
